version: '3.9'
services:
  simulator:
    platform: linux/amd64
    build: ./simulator
    environment:
      - HOST=http://operator
      - PORT=5000
    depends_on:
      - operator
  monitor:
    platform: linux/amd64
    build: ./monitor
    environment:
      - "REACT_APP_OPERATOR_ADDR=http://localhost:5000"
    ports:
      - 3000:3000
    depends_on:
      - operator
  operator:
    platform: linux/amd64
    build: ./operator
    environment:
      - HOST=operator
      - PORT=5000
    ports:
      - 5000:5000
